### ISSUE TITLE
crawlt aber erstellt keine crawljobs

### ISSUE THREAD

**Issue by Gutz-Pilz** [rix1337/docker-rsscrawler#16]
hi rix1337,

dein fix von letztens funktioniert.
er crawlt. schreibt das gefundene auch schön in den log.
erstellt aber kein crawljb dateien im folderwatch ordner.

hier meine config:
```
  rsscrawler:
    container_name: rsscrawler
    image: rix1337/docker-rsscrawler
    ports:
      - "6060:9090"
    volumes:
      - '/root/.configs/.rsscrawler/:/config:rw'
      - '/root/.configs/.jdownloader2/:/jd2:rw'
    environment:
      - PUID=1000
      - PGID=100
      - LOGLEVEL=DEBUG
    restart: always
````
